defaults: &defaults
  docker:
    - image: golang:1.11.4
  environment:
    GO111MODULE: "on"
  working_directory: /go/src/github.com/ernoaapa/kubectl-warp

version: 2
jobs:
  test:
    <<: *defaults
    steps:
      - checkout
      
      - run: "! go fmt -l pkg cmd 2>&1 | read"
      - run: go vet ./...
      - run: go test ./...

  build:
    <<: *defaults
    steps:
      - checkout

      - run: go build .

      - run: wget -qO- https://github.com/goreleaser/goreleaser/releases/download/v0.95.0/goreleaser_Linux_x86_64.tar.gz | tar xvz -C /usr/local/bin
      - run: goreleaser --snapshot

  publish:
    <<: *defaults
    steps:
      - checkout

      - run: go build .

      - run: wget -qO- https://github.com/goreleaser/goreleaser/releases/download/v0.95.0/goreleaser_Linux_x86_64.tar.gz | tar xvz -C /usr/local/bin
      - run: goreleaser

workflows:
  version: 2
  build_and_test:
    jobs:
      - test
              
      - build:
          requires:
            - test

      - publish:
          requires:
            - build
          
          # Don't run when branches updates, only when tags get created
          filters:
            tags:
              only:
                - /v.*/
